### ISSUE TITLE
Instalation and implementation

### ISSUE THREAD

**Issue by hdkcreative** [gomonkey/yii2-easy-uploader#1]
hi! 

cool plugin ! 

but...

```
Problem 1
    - The requested package gomonkey/yii2-easy-uploader * is satisfiable by gomonkey/yii2-easy-uploader[1.0.1.x-dev, dev-master] but these conflict with your requirements or minimum-stability.

```

addition.... in the the  home page...

**you need add ,**

'rename' => true, // Rename file 
            'random' => 12 (  **HERE    ,**    ) // random  . .      ;)

**Comment by gabriele-carbonai** [comment]
Sorry for delay and thank you for reporting the issue in readme.md.
For install the plugin, you must change stability in your composer.json file

**Comment by hdkcreative** [comment]
thank you @gomonkey
